// Mock orders data for the Operations orders module.
// Keep static data here and consume it through services/api/orders.js.

export const ORDER_STATUS_OPTIONS = [
    "All",
    "Pending",
    "Assigned",
    "In Transit",
    "Out for Delivery",
    "Delivered",
    "Failed",
    "Returned",
];

export const ORDER_PRIORITY_OPTIONS = ["Normal", "Express"];

export const ORDER_PAYMENT_OPTIONS = ["Prepaid", "COD"];

export const IMPORT_NOTE =
    "Live tracking links will be auto-generated and sent to customers via SMS, WhatsApp, and Email upon import.";

export const ordersSeedData = [
    {
        id: "ORD-4501",
        customerName: "Ahmad Electronics",
        customerPhone: "+20 100 111 2222",
        customerEmail: "ahmad@electronics.eg",
        address: "El Hegaz St, Heliopolis",
        weightKg: 12.5,
        volumeM3: 0.8,
        paymentType: "Prepaid",
        paymentWindow: "09:00-11:00",
        priority: "Express",
        status: "Pending",
        trackingLink: "https://track.fleetops.eg/4501",
        driver: null,
        vehicleId: null,
        createdAt: "Apr 14, 2026",
        liveTrackingMessage:
            "Order not yet dispatched - tracking will activate when driver picks up",
        liveTrackingHint:
            "Customer can view all status changes at their tracking link.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 08:01 AM",
                content:
                    "Tracking link + order confirmation sent to +20 100 111 2222",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 08:01 AM",
                content:
                    "Tracking link + order confirmation sent to +20 100 111 2222",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 08:02 AM",
                content:
                    "Tracking link + order confirmation sent to ahmad@electronics.eg",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description:
                    "Auto-tracking link generated and sent to customer",
                at: "Apr 14, 08:00 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4502",
        customerName: "Fresh Market Egypt",
        customerPhone: "+20 100 333 4444",
        customerEmail: "ops@freshmarket.eg",
        address: "Abbas El Akkad St, Nasr City",
        weightKg: 45,
        volumeM3: 2.1,
        paymentType: "COD (EGP 1,250)",
        paymentWindow: "10:00-14:00",
        priority: "Normal",
        status: "Assigned",
        trackingLink: "https://track.fleetops.eg/4502",
        driver: { name: "Layla Ahmed", code: "TRK-015", initials: "LA" },
        vehicleId: "TRK-015",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Driver assigned - pickup is scheduled within the delivery window",
        liveTrackingHint: "Customer will receive dispatch and movement updates automatically.",
        notificationsSummary: { sent: 0, total: 3, failed: 3 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 09:15 AM",
                content: "Dispatch reminder queued for +20 100 333 4444",
                status: "Failed",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 09:16 AM",
                content: "Dispatch reminder queued for +20 100 333 4444",
                status: "Failed",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 09:16 AM",
                content: "Dispatch reminder queued for ops@freshmarket.eg",
                status: "Failed",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "COD order added to dispatch queue",
                at: "Apr 14, 08:35 AM",
                notified: true,
            },
            {
                title: "Driver Assigned",
                description: "Layla Ahmed accepted the pickup task",
                at: "Apr 14, 09:10 AM",
                notified: false,
            },
        ],
    },
    {
        id: "ORD-4503",
        customerName: "Tech Solutions",
        customerPhone: "+20 100 555 6666",
        customerEmail: "dispatch@techsolutions.eg",
        address: "Makram Ebeid St, Nasr City",
        weightKg: 3.2,
        volumeM3: 0.2,
        paymentType: "Prepaid",
        paymentWindow: "08:00-10:00",
        priority: "Normal",
        status: "In Transit",
        trackingLink: "https://track.fleetops.eg/4503",
        driver: { name: "Hassan Youssef", code: "TRK-031", initials: "HY" },
        vehicleId: "TRK-031",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Vehicle is en route to the customer district",
        liveTrackingHint: "Customer currently sees the route progress and latest checkpoint.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 09:05 AM",
                content: "Pickup confirmed and order is now in transit",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 09:05 AM",
                content: "Pickup confirmed and order is now in transit",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 09:06 AM",
                content: "Pickup confirmed and order is now in transit",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Prepaid shipment created from customer portal",
                at: "Apr 14, 07:55 AM",
                notified: true,
            },
            {
                title: "Driver Assigned",
                description: "Hassan Youssef assigned to route CAI-2",
                at: "Apr 14, 08:10 AM",
                notified: true,
            },
            {
                title: "In Transit",
                description: "Pickup completed and parcel scanned on vehicle",
                at: "Apr 14, 09:00 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4504",
        customerName: "Home Decor Plus",
        customerPhone: "+20 100 777 8888",
        customerEmail: "support@homedecor.eg",
        address: "90th Street, New Cairo",
        weightKg: 28,
        volumeM3: 1.3,
        paymentType: "Prepaid",
        paymentWindow: "12:00-16:00",
        priority: "Express",
        status: "Out for Delivery",
        trackingLink: "https://track.fleetops.eg/4504",
        driver: { name: "Mohammed Ali", code: "TRK-042", initials: "MA" },
        vehicleId: "TRK-042",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Driver is on the final leg and heading to the delivery stop",
        liveTrackingHint: "Customer can see the driver's latest live position on the map.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 11:32 AM",
                content: "Driver is approaching the delivery location",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 11:32 AM",
                content: "Driver is approaching the delivery location",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 11:33 AM",
                content: "Driver is approaching the delivery location",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Express furniture order created",
                at: "Apr 14, 08:20 AM",
                notified: true,
            },
            {
                title: "In Transit",
                description: "Vehicle departed warehouse with package loaded",
                at: "Apr 14, 10:40 AM",
                notified: true,
            },
            {
                title: "Out for Delivery",
                description: "Driver left previous stop and is heading to customer",
                at: "Apr 14, 11:30 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4505",
        customerPhone: "+20 100 999 0000",
        customerEmail: "receiving@aldohadairy.eg",
        customerName: "Al Doha Dairy",
        address: "Road 9, Maadi",
        weightKg: 85,
        volumeM3: 5.2,
        paymentType: "COD",
        paymentWindow: "06:00-08:00",
        priority: "Normal",
        status: "Delivered",
        trackingLink: "https://track.fleetops.eg/4505",
        driver: { name: "Omar Khalid", code: "TRK-023", initials: "OK" },
        vehicleId: "TRK-023",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Order was delivered successfully and confirmed by recipient",
        liveTrackingHint: "Tracking view now shows the completed handoff event.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 07:58 AM",
                content: "Delivery completed successfully",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 07:58 AM",
                content: "Delivery completed successfully",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 07:59 AM",
                content: "Delivery completed successfully",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Cold-chain route prepared for morning dispatch",
                at: "Apr 14, 05:30 AM",
                notified: true,
            },
            {
                title: "Out for Delivery",
                description: "Vehicle left depot with refrigerated cargo",
                at: "Apr 14, 06:15 AM",
                notified: true,
            },
            {
                title: "Delivered",
                description: "Receiver signed and temperature compliance confirmed",
                at: "Apr 14, 07:55 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4506",
        customerName: "MedSupply Egypt",
        customerPhone: "+20 100 222 3333",
        customerEmail: "ops@medsupply.eg",
        address: "Medical District, New Cairo",
        weightKg: 5.8,
        volumeM3: 0.5,
        paymentType: "Prepaid",
        paymentWindow: "09:00-17:00",
        priority: "Normal",
        status: "Delivered",
        trackingLink: "https://track.fleetops.eg/4506",
        driver: { name: "Layla Ahmed", code: "TRK-015", initials: "LA" },
        vehicleId: "TRK-015",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Medical supplies delivered and proof-of-delivery uploaded",
        liveTrackingHint: "Customer can review the full status history at the tracking page.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 01:20 PM",
                content: "Proof of delivery shared with customer",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 01:20 PM",
                content: "Proof of delivery shared with customer",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 01:21 PM",
                content: "Proof of delivery shared with customer",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Healthcare shipment booked for same-day delivery",
                at: "Apr 14, 08:10 AM",
                notified: true,
            },
            {
                title: "In Transit",
                description: "Driver departed pharmacy pickup point",
                at: "Apr 14, 10:00 AM",
                notified: true,
            },
            {
                title: "Delivered",
                description: "Items handed to clinic receiving desk",
                at: "Apr 14, 01:15 PM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4507",
        customerName: "Nile Parts Co",
        customerPhone: "+20 100 444 5555",
        customerEmail: "warehouse@nileparts.eg",
        address: "Industrial Zone 2, 6th of October",
        weightKg: 120,
        volumeM3: 6.4,
        paymentType: "Prepaid",
        paymentWindow: "08:00-12:00",
        priority: "Express",
        status: "In Transit",
        trackingLink: "https://track.fleetops.eg/4507",
        driver: { name: "Hassan Youssef", code: "TRK-031", initials: "HY" },
        vehicleId: "TRK-031",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Heavy spare parts shipment is moving between checkpoints",
        liveTrackingHint: "Tracking remains visible while the route is active.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 09:45 AM",
                content: "Shipment departed warehouse and is in transit",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 09:45 AM",
                content: "Shipment departed warehouse and is in transit",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 09:46 AM",
                content: "Shipment departed warehouse and is in transit",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Express spare parts order created by operations team",
                at: "Apr 14, 07:40 AM",
                notified: true,
            },
            {
                title: "Driver Assigned",
                description: "Hassan Youssef assigned heavy load transport",
                at: "Apr 14, 08:05 AM",
                notified: true,
            },
            {
                title: "In Transit",
                description: "Vehicle passed warehouse exit checkpoint",
                at: "Apr 14, 09:40 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4508",
        customerName: "Green Garden",
        customerPhone: "+20 100 666 7777",
        customerEmail: "hello@greengarden.eg",
        address: "El Nozha, Heliopolis",
        weightKg: 15,
        volumeM3: 0.9,
        paymentType: "COD",
        paymentWindow: "10:00-12:00",
        priority: "Normal",
        status: "Failed",
        trackingLink: "https://track.fleetops.eg/4508",
        driver: { name: "Mohammed Ali", code: "TRK-042", initials: "MA" },
        vehicleId: "TRK-042",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Delivery attempt failed and customer follow-up is required",
        liveTrackingHint: "Customer sees the failed attempt note and reschedule prompt.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 11:48 AM",
                content: "Delivery attempt failed due to recipient unavailable",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 11:48 AM",
                content: "Delivery attempt failed due to recipient unavailable",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 11:49 AM",
                content: "Delivery attempt failed due to recipient unavailable",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Out for Delivery",
                description: "Driver arrived at gated property",
                at: "Apr 14, 11:10 AM",
                notified: true,
            },
            {
                title: "Delivery Failed",
                description: "Recipient unavailable at the location",
                at: "Apr 14, 11:45 AM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4509",
        customerName: "Daily Bread",
        customerPhone: "+20 100 888 9999",
        customerEmail: "store@dailybread.eg",
        address: "Road 9, Maadi",
        weightKg: 22,
        volumeM3: 1.1,
        paymentType: "Prepaid",
        paymentWindow: "09:00-13:00",
        priority: "Normal",
        status: "Returned",
        trackingLink: "https://track.fleetops.eg/4509",
        driver: { name: "Omar Khalid", code: "TRK-023", initials: "OK" },
        vehicleId: "TRK-023",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Order returned to origin after customer rejection",
        liveTrackingHint: "Return workflow updates are visible to the customer.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 12:18 PM",
                content: "Order returned to origin and support will follow up",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 12:18 PM",
                content: "Order returned to origin and support will follow up",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 12:19 PM",
                content: "Order returned to origin and support will follow up",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Out for Delivery",
                description: "Driver reached bakery branch",
                at: "Apr 14, 10:45 AM",
                notified: true,
            },
            {
                title: "Returned",
                description: "Customer rejected order due to schedule mismatch",
                at: "Apr 14, 12:15 PM",
                notified: true,
            },
        ],
    },
    {
        id: "ORD-4510",
        customerName: "Quick Bites",
        customerPhone: "+20 100 000 1111",
        customerEmail: "ops@quickbites.eg",
        address: "26th of July St, Zamalek",
        weightKg: 9.5,
        volumeM3: 0.6,
        paymentType: "Prepaid",
        paymentWindow: "11:00-15:00",
        priority: "Express",
        status: "Out for Delivery",
        trackingLink: "https://track.fleetops.eg/4510",
        driver: { name: "Layla Ahmed", code: "TRK-015", initials: "LA" },
        vehicleId: "TRK-015",
        createdAt: "Apr 14, 2026",
        liveTrackingMessage: "Courier is approaching the final customer stop",
        liveTrackingHint: "The customer map updates continuously until handoff.",
        notificationsSummary: { sent: 3, total: 3, failed: 0 },
        notifications: [
            {
                channel: "SMS",
                icon: "smartphone",
                sentAt: "Apr 14, 12:02 PM",
                content: "Driver is 15 minutes away from the destination",
                status: "Sent",
            },
            {
                channel: "WhatsApp",
                icon: "message-circle",
                sentAt: "Apr 14, 12:02 PM",
                content: "Driver is 15 minutes away from the destination",
                status: "Sent",
            },
            {
                channel: "Email",
                icon: "mail",
                sentAt: "Apr 14, 12:03 PM",
                content: "Driver is 15 minutes away from the destination",
                status: "Sent",
            },
        ],
        timeline: [
            {
                title: "Order Created",
                description: "Express food-service replenishment created",
                at: "Apr 14, 09:35 AM",
                notified: true,
            },
            {
                title: "Driver Assigned",
                description: "Layla Ahmed assigned downtown route",
                at: "Apr 14, 10:00 AM",
                notified: true,
            },
            {
                title: "Out for Delivery",
                description: "Delivery vehicle entered downtown service zone",
                at: "Apr 14, 11:58 AM",
                notified: true,
            },
        ],
    },
];
