export const ROUTE_STATUS_OPTIONS = [
    "All",
    "Active",
    "In Transit",
    "Completed",
    "Pending",
    "Cancelled",
];

export const ROUTE_SHIFT_OPTIONS = ["All Shifts", "Morning", "Evening", "Night"];

export const ROUTE_DATE_OPTIONS = [
    "All Dates",
    "Apr 14, 2026",
    "Apr 13, 2026",
    "Apr 12, 2026",
    "Apr 11, 2026",
];

const baseRoutes = [
    {
        id: "R-1001",
        driverName: "Mohammed Ali",
        driverInitials: "MA",
        vehicleId: "TRK-042",
        vehicleType: "Heavy",
        status: "Active",
        shift: "Morning",
        completedStops: 1,
        totalStops: 12,
        progress: 8,
        distanceKm: 31,
        startTime: "6:24 AM",
        eta: "15:23 PM",
        etaStatus: "On Time",
        date: "Apr 14, 2026",
        version: 1,
        totalWeightKg: 410,
        totalVolumeM3: 8.2,
        eventTime: "07:53 AM",
        playbackFrames: 34,
        playbackStopsDelivered: 1,
        playbackStopsRemaining: 11,
        linePoints: [14, 28, 20, 34, 25, 17, 31],
        eventLog: [
            { title: "Departed from depot", time: "07:53 AM" },
            { title: "Reached stop 1 checkpoint", time: "08:21 AM" },
        ],
        stops: [
            createStop(1, "Fresh Market Egypt", "Abbas El Akkad St", "ORD-5101", "09:00", "09:08", true),
            createStop(2, "Green Garden", "El Nozha", "ORD-5102", "09:18", "--", false),
            createStop(3, "Tech Solutions", "Makram Ebeid St", "ORD-5103", "09:33", "--", false),
            createStop(4, "Office Supplies", "Obour Gate", "ORD-5104", "09:48", "--", false),
            createStop(5, "MedSupply Egypt", "New Cairo", "ORD-5105", "10:05", "--", false),
            createStop(6, "Nile Parts", "6th of October Industrial Zone", "ORD-5106", "10:25", "--", false),
            createStop(7, "Daily Bread", "Maadi", "ORD-5107", "10:42", "--", false),
            createStop(8, "Quick Bites", "Downtown", "ORD-5108", "11:05", "--", false),
            createStop(9, "Ahmad Electronics", "Heliopolis", "ORD-5109", "11:22", "--", false),
            createStop(10, "Pharma Direct", "Dokki", "ORD-5110", "11:40", "--", false),
            createStop(11, "Home Decor Plus", "Zamalek", "ORD-5111", "12:00", "--", false),
            createStop(12, "Al Doha Dairy", "Ring Road", "ORD-5112", "12:18", "--", false),
        ],
    },
    {
        id: "R-1002",
        driverName: "Sara Hassan",
        driverInitials: "SH",
        vehicleId: "TRK-015",
        vehicleType: "Light",
        status: "Completed",
        shift: "Morning",
        completedStops: 19,
        totalStops: 19,
        progress: 100,
        distanceKm: 56,
        startTime: "6:12 AM",
        eta: "--",
        etaStatus: "",
        date: "Apr 14, 2026",
        version: 2,
        totalWeightKg: 625,
        totalVolumeM3: 10.6,
        eventTime: "07:53 AM",
        playbackFrames: 59,
        playbackStopsDelivered: 19,
        playbackStopsRemaining: 0,
        linePoints: [18, 32, 12, 36, 22, 9, 28],
        eventLog: [
            { title: "Departed from depot", time: "07:53 AM" },
            { title: "Final stop delivered", time: "11:32 AM" },
        ],
        stops: [
            createStop(1, "Fresh Market Egypt", "New Cairo", "ORD-15100", "09:00", "09:05", true),
            createStop(2, "Green Garden", "Abbas El Akkad St", "ORD-15101", "09:15", "09:21", true),
            createStop(3, "Daily Bread", "Maadi", "ORD-15102", "09:30", "09:27", true),
            createStop(4, "Office Supplies", "Obour Gate", "ORD-15103", "09:45", "09:44", true),
            createStop(5, "Pharma Direct", "El Nozha", "ORD-15104", "10:00", "10:03", true),
            createStop(6, "Tech Solutions", "Downtown", "ORD-15105", "10:15", "10:20", true),
            createStop(7, "Al Doha Dairy", "Dokki", "ORD-15106", "10:30", "10:34", true),
            createStop(8, "MedSupply Egypt", "Obour Industrial Zone", "ORD-15107", "10:45", "10:51", true),
            createStop(9, "Nile Parts", "Dokki", "ORD-15108", "11:00", "11:01", true),
            createStop(10, "Home Decor Plus", "Zamalek", "ORD-15109", "11:15", "11:20", true),
            createStop(11, "Ahmad Electronics", "Sheikh Zayed", "ORD-15110", "11:30", "11:32", true),
        ],
    },
    {
        id: "R-1003",
        driverName: "Omar Khalid",
        driverInitials: "OK",
        vehicleId: "TRK-023",
        vehicleType: "Refrigerated",
        status: "Completed",
        shift: "Morning",
        completedStops: 9,
        totalStops: 9,
        progress: 100,
        distanceKm: 84,
        startTime: "6:06 AM",
        eta: "--",
        etaStatus: "",
        date: "Apr 14, 2026",
        version: 1,
        totalWeightKg: 702,
        totalVolumeM3: 12.1,
        eventTime: "08:04 AM",
        playbackFrames: 42,
        playbackStopsDelivered: 9,
        playbackStopsRemaining: 0,
        linePoints: [12, 20, 29, 14, 24, 11],
        eventLog: [{ title: "Route completed", time: "12:08 PM" }],
        stops: [
            createStop(1, "Al Doha Dairy", "6th of October", "ORD-15200", "08:30", "08:28", true),
            createStop(2, "Quick Bites", "Airport Road", "ORD-15201", "08:55", "08:54", true),
            createStop(3, "Daily Bread", "90th Street", "ORD-15202", "09:15", "09:12", true),
        ],
    },
    {
        id: "R-1004",
        driverName: "Fatima Noor",
        driverInitials: "FN",
        vehicleId: "TRK-007",
        vehicleType: "Heavy",
        status: "Active",
        shift: "Evening",
        completedStops: 1,
        totalStops: 21,
        progress: 5,
        distanceKm: 49,
        startTime: "6:26 AM",
        eta: "15:31 PM",
        etaStatus: "On Time",
        date: "Apr 14, 2026",
        version: 1,
        totalWeightKg: 380,
        totalVolumeM3: 7.4,
        eventTime: "08:00 AM",
        playbackFrames: 18,
        playbackStopsDelivered: 1,
        playbackStopsRemaining: 20,
        linePoints: [10, 14, 19, 22, 18, 27],
        eventLog: [{ title: "Route started", time: "08:00 AM" }],
        stops: [createStop(1, "Green Garden", "Heliopolis", "ORD-15300", "09:00", "09:12", true)],
    },
    {
        id: "R-1005",
        driverName: "Hassan Youssef",
        driverInitials: "HY",
        vehicleId: "TRK-031",
        vehicleType: "Light",
        status: "In Transit",
        shift: "Morning",
        completedStops: 4,
        totalStops: 9,
        progress: 44,
        distanceKm: 85,
        startTime: "6:44 AM",
        eta: "16:47 PM",
        etaStatus: "On Time",
        date: "Apr 14, 2026",
        version: 1,
        totalWeightKg: 291,
        totalVolumeM3: 6.3,
        eventTime: "08:20 AM",
        playbackFrames: 27,
        playbackStopsDelivered: 4,
        playbackStopsRemaining: 5,
        linePoints: [13, 15, 18, 22, 25, 16, 20],
        eventLog: [{ title: "Vehicle reached district cluster", time: "10:14 AM" }],
        stops: [
            createStop(1, "Pharma Direct", "Mohandessin", "ORD-15400", "08:45", "08:43", true),
            createStop(2, "Tech Solutions", "Makram Ebeid", "ORD-15401", "09:05", "09:02", true),
            createStop(3, "Home Decor Plus", "Salah Salem Rd", "ORD-15402", "09:28", "09:31", true),
            createStop(4, "Ahmad Electronics", "Heliopolis", "ORD-15403", "09:50", "09:54", true),
            createStop(5, "Daily Bread", "Shubra", "ORD-15404", "10:15", "--", false),
        ],
    },
    {
        id: "R-1006",
        driverName: "Layla Ahmed",
        driverInitials: "LA",
        vehicleId: "TRK-019",
        vehicleType: "Refrigerated",
        status: "Completed",
        shift: "Evening",
        completedStops: 19,
        totalStops: 19,
        progress: 100,
        distanceKm: 35,
        startTime: "7:22 AM",
        eta: "--",
        etaStatus: "",
        date: "Apr 13, 2026",
        version: 1,
        totalWeightKg: 488,
        totalVolumeM3: 8.7,
        eventTime: "08:02 AM",
        playbackFrames: 51,
        playbackStopsDelivered: 19,
        playbackStopsRemaining: 0,
        linePoints: [18, 25, 31, 22, 17, 28],
        eventLog: [{ title: "Route completed", time: "01:08 PM" }],
        stops: [createStop(1, "Quick Bites", "Mokattam", "ORD-15500", "08:15", "08:16", true)],
    },
    {
        id: "R-1007",
        driverName: "Khalid Tariq",
        driverInitials: "KT",
        vehicleId: "TRK-050",
        vehicleType: "Heavy",
        status: "Pending",
        shift: "Morning",
        completedStops: 0,
        totalStops: 23,
        progress: 0,
        distanceKm: 94,
        startTime: "--",
        eta: "--",
        etaStatus: "",
        date: "Apr 13, 2026",
        version: 1,
        totalWeightKg: 555,
        totalVolumeM3: 11.9,
        eventTime: "06:50 AM",
        playbackFrames: 0,
        playbackStopsDelivered: 0,
        playbackStopsRemaining: 23,
        linePoints: [10, 12, 14, 16, 20, 24],
        eventLog: [{ title: "Route waiting for dispatch release", time: "06:50 AM" }],
        stops: [createStop(1, "Nile Parts", "Obour Warehouse Zone", "ORD-15600", "09:00", "--", false)],
    },
    {
        id: "R-1008",
        driverName: "Nora Mansoor",
        driverInitials: "NM",
        vehicleId: "TRK-028",
        vehicleType: "Light",
        status: "Completed",
        shift: "Morning",
        completedStops: 23,
        totalStops: 23,
        progress: 100,
        distanceKm: 99,
        startTime: "7:22 AM",
        eta: "--",
        etaStatus: "",
        date: "Apr 13, 2026",
        version: 2,
        totalWeightKg: 430,
        totalVolumeM3: 9.5,
        eventTime: "08:30 AM",
        playbackFrames: 64,
        playbackStopsDelivered: 23,
        playbackStopsRemaining: 0,
        linePoints: [21, 14, 26, 18, 31, 22],
        eventLog: [{ title: "All stops delivered", time: "03:06 PM" }],
        stops: [createStop(1, "Fresh Market Egypt", "Ring Road", "ORD-15700", "08:40", "08:39", true)],
    },
    {
        id: "R-1009",
        driverName: "Mohammed Ali",
        driverInitials: "MA",
        vehicleId: "TRK-042",
        vehicleType: "Refrigerated",
        status: "Active",
        shift: "Evening",
        completedStops: 6,
        totalStops: 15,
        progress: 40,
        distanceKm: 49,
        startTime: "7:23 AM",
        eta: "16:52 PM",
        etaStatus: "On Time",
        date: "Apr 13, 2026",
        version: 1,
        totalWeightKg: 512,
        totalVolumeM3: 9.8,
        eventTime: "09:04 AM",
        playbackFrames: 23,
        playbackStopsDelivered: 6,
        playbackStopsRemaining: 9,
        linePoints: [16, 28, 14, 20, 27, 18],
        eventLog: [{ title: "Driver cleared stop cluster B", time: "11:42 AM" }],
        stops: [createStop(1, "MedSupply Egypt", "North Zone, New Cairo", "ORD-15800", "09:25", "09:19", true)],
    },
    {
        id: "R-1010",
        driverName: "Sara Hassan",
        driverInitials: "SH",
        vehicleId: "TRK-015",
        vehicleType: "Heavy",
        status: "Completed",
        shift: "Morning",
        completedStops: 11,
        totalStops: 11,
        progress: 100,
        distanceKm: 51,
        startTime: "7:53 AM",
        eta: "--",
        etaStatus: "",
        date: "Apr 13, 2026",
        version: 2,
        totalWeightKg: 625,
        totalVolumeM3: 10.6,
        eventTime: "07:53 AM",
        playbackFrames: 59,
        playbackStopsDelivered: 11,
        playbackStopsRemaining: 0,
        linePoints: [20, 34, 12, 39, 24, 9, 29],
        eventLog: [{ title: "Departed from depot", time: "07:53 AM" }],
        stops: [
            createStop(1, "Fresh Market Egypt", "New Cairo", "ORD-15100", "09:00", "09:05", true),
            createStop(2, "Green Garden", "Abbas El Akkad St", "ORD-15101", "09:15", "09:21", true),
            createStop(3, "Daily Bread", "Maadi", "ORD-15102", "09:30", "09:27", true),
            createStop(4, "Office Supplies", "Obour Gate", "ORD-15103", "09:45", "09:44", true),
            createStop(5, "Pharma Direct", "El Nozha", "ORD-15104", "10:00", "10:03", true),
            createStop(6, "Tech Solutions", "Downtown", "ORD-15105", "10:15", "10:20", true),
            createStop(7, "Al Doha Dairy", "Dokki", "ORD-15106", "10:30", "10:34", true),
            createStop(8, "MedSupply Egypt", "Obour Industrial Zone", "ORD-15107", "10:45", "10:51", true),
            createStop(9, "Nile Parts", "Dokki", "ORD-15108", "11:00", "11:01", true),
            createStop(10, "Home Decor Plus", "Zamalek", "ORD-15109", "11:15", "11:20", true),
            createStop(11, "Ahmad Electronics", "Sheikh Zayed", "ORD-15110", "11:30", "11:32", true),
        ],
    },
];

export const routesSeedData = [
    ...baseRoutes,
    ...Array.from({ length: 35 }, (_, index) => createGeneratedRoute(index + 11)),
];

function createStop(index, customer, address, orderId, planned, actual, delivered) {
    return {
        index,
        customer,
        address,
        orderId,
        planned,
        actual,
        delivered,
    };
}

function createGeneratedRoute(routeNumber) {
    const numericId = 1000 + routeNumber;
    const statuses = ["Active", "Completed", "In Transit", "Pending", "Cancelled"];
    const shifts = ["Morning", "Evening", "Night"];
    const drivers = [
        ["Mazen Adel", "MA"],
        ["Reem Fawzi", "RF"],
        ["Yousef Adel", "YA"],
        ["Lina Samir", "LS"],
        ["Tariq Nabil", "TN"],
    ];
    const vehicleTypes = ["Light", "Heavy", "Refrigerated"];
    const dates = ["Apr 14, 2026", "Apr 13, 2026", "Apr 12, 2026", "Apr 11, 2026"];
    const status = statuses[routeNumber % statuses.length];
    const totalStops = 8 + (routeNumber % 18);
    const completedStops =
        status === "Completed"
            ? totalStops
            : status === "Pending" || status === "Cancelled"
              ? 0
              : Math.max(1, Math.floor(totalStops * ((routeNumber % 7) + 1) / 10));
    const progress =
        status === "Completed"
            ? 100
            : status === "Pending" || status === "Cancelled"
              ? 0
              : Math.round((completedStops / totalStops) * 100);
    const driver = drivers[routeNumber % drivers.length];
    const date = dates[routeNumber % dates.length];

    return {
        id: `R-${numericId}`,
        driverName: driver[0],
        driverInitials: driver[1],
        vehicleId: `TRK-${String(11 + routeNumber).padStart(3, "0")}`,
        vehicleType: vehicleTypes[routeNumber % vehicleTypes.length],
        status,
        shift: shifts[routeNumber % shifts.length],
        completedStops,
        totalStops,
        progress,
        distanceKm: 24 + routeNumber * 3,
        startTime: status === "Pending" ? "--" : `${6 + (routeNumber % 4)}:${String(12 + routeNumber).padStart(2, "0")} AM`,
        eta: status === "Completed" || status === "Pending" || status === "Cancelled" ? "--" : `1${routeNumber % 7}:4${routeNumber % 10} PM`,
        etaStatus: status === "Cancelled" ? "Delayed" : status === "Pending" || status === "Completed" ? "" : "On Time",
        date,
        version: (routeNumber % 3) + 1,
        totalWeightKg: 180 + routeNumber * 11,
        totalVolumeM3: Number((4.4 + routeNumber * 0.2).toFixed(1)),
        eventTime: "08:00 AM",
        playbackFrames: 20 + routeNumber,
        playbackStopsDelivered: completedStops,
        playbackStopsRemaining: totalStops - completedStops,
        linePoints: [14, 26, 12, 31, 19, 27],
        eventLog: [{ title: status === "Completed" ? "Route completed" : "Route checkpoint updated", time: "10:20 AM" }],
        stops: [createStop(1, "Auto Stop", "Route Grid", `ORD-${16000 + routeNumber}`, "09:00", completedStops ? "09:02" : "--", completedStops > 0)],
    };
}
